workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17

    scripts:
      - name: Clear Flutter and Gradle Cache Forcefully
        script: |
          flutter pub cache clean --force
          rm -rf ~/.gradle/caches
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
