workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          cd planets_explorer
          flutter packages pub get
      - name: Build Android APK
        script: |
          cd planets_explorer
          flutter build apk --release
    artifacts:
      - planets_explorer/build/app/outputs/flutter-apk/*.apk
