name: planets_explorer
description: "Planets Explorer: Solar System Guide"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.11
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.2
  permission_handler: 11.3.1
  permission_handler_android: 11.3.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
